package com.example.libraryproject;

import android.content.Context;
import android.content.SharedPreferences;

import com.google.gson.Gson;

import java.util.ArrayList;
//class made for instantiating books in our all books

public class BookBase {
    private static BookBase instance;

    public BookBase() {

    }

    public static ArrayList initBase() {
        //adding all the books into this new array list and then returning it to the /Utils class and Shared Preferences
        ArrayList<Book> books = new ArrayList<>();
        books.add(new Book(1, "The Plague", "Alber Camus", 272, "https://images-na.ssl-images-amazon.com/images/I/91aLlM9Do2L._AC_UL320_SR208,320_.jpg", "The Plague is Albert Camus's world-renowned fable of fear and courage", "The townspeople of Oran are in the grip of a deadly plague, which condemns its victims to a swift and horrifying death. Fear, isolation and claustrophobia follow as they are forced into quarantine. Each person responds in their own way to the lethal disease: some resign themselves to fate, some seek blame, and a few, like Dr Rieux, resist the terror.\n" +
                "\n" +
                "An immediate triumph when it was published in 1947, The Plague is in part an allegory of France's suffering under the Nazi occupation, and a story of bravery and determination against the precariousness of human existence."));
        books.add(new Book(2, "My Brilliant Friend", "Elena Ferante", 336, "https://pagesofhackney.co.uk/webshop/wp-content/uploads/2020/04/unnamed-1.jpg", "the first volume in the New York Times-bestselling \"enduring masterpiece\" about a lifelong friendship between two women from Naples (The Atlantic).", "Beginning in the 1950s in a poor but vibrant neighborhood on the outskirts of Naples, Elena Ferrante's four-volume story spans almost sixty years, as its main characters, the fiery and unforgettable Lila and the bookish narrator, Elena, become women, wives, mothers, and leaders, all the while maintaining a complex and at times conflicted friendship. This first novel in the series follows Lila and Elena from their fateful meeting as ten-year-olds through their school years and adolescence."));
        books.add(new Book(3, "1984", " George Orwell", 400, "https://images-na.ssl-images-amazon.com/images/I/51ldXBWwuyL._SX324_BO1,204,203,200_.jpg", "1984 is George Orwell's terrifying vision of a totalitarian future in which everything and everyone is slave to a tyrannical regime.", "Winston Smith works for the Ministry of Truth in London, chief city of Airstrip One. Big Brother stares out from every poster, the Thought Police uncover every act of betrayal. When Winston finds love with Julia, he discovers that life does not have to be dull and deadening, and awakens to new possibilities. Despite the police helicopters that hover and circle overhead, Winston and Julia begin to question the Party; they are drawn towards conspiracy. Yet Big Brother will not tolerate dissent - even in the mind. For those with original thoughts they invented Room 101. . ."));
        books.add(new Book(4, "The Handmaid's Tale", "Margaret Atwood", 336, "https://images-na.ssl-images-amazon.com/images/I/41TI0xCRV6L._SX322_BO1,204,203,200_.jpg", "Masterfully conceived and executed, this haunting vision of the future places Margaret Atwood at the forefront of dystopian fiction.", "Offred is a Handmaid in The Republic of Gilead, a religious totalitarian state in what was formerly known as the United States. She is placed in the household of The Commander, Fred Waterford - her assigned name, Offred, means 'of Fred'. She has only one function: to breed. If Offred refuses to enter into sexual servitude to repopulate a devastated world, she will be hanged. Yet even a repressive state cannot eradicate hope and desire. As she recalls her pre-revolution life in flashbacks, Offred must navigate through the terrifying landscape of torture and persecution in the present day, and between two men upon which her future hangs."));
        books.add(new Book(5, "The Catcher in the Rye", "J. D. Salinger", 224, "https://images-na.ssl-images-amazon.com/images/I/413kD8lCVBL._SX301_BO1,204,203,200_.jpg", "The \"brilliant, funny, meaningful novel\"", "\"If you really want to hear about it, the first thing you'll probably want to know is where I was born, and what my lousy childhood was like, and how my parents were occupied and all before they had me, and all that David Copperfield kind of crap, but I don't feel like going into it, if you want to know the truth.\"\n" +
                "The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caufield. Through circumstances that tend to preclude adult, secondhand description, he leaves his prep school in Pennsylvania and goes underground in New York City for three days."));
        books.add(new Book(6, "Crime and Punishment", " Fyodor Dostoevsky", 528, "https://m.media-amazon.com/images/I/41AM6pjaZhL.jpg", "Crime and Punishment is one of the greatest and most readable novels ever written.", "From that moment on, we share his conflicting feelings of self-loathing and pride, of contempt for and need of others, and of terrible despair and hope of redemption: and, in a remarkable transformation of the detective novel, we follow his agonised efforts to probe and confront both his own motives for, and the consequences of, his crime.\n" +
                "\n" +
                "The result is a tragic novel built out of a series of supremely dramatic scenes that illuminate the eternal conflicts at the heart of human existence: most especially our desire for self-expression and self-fulfilment, as against the constraints of morality and human laws; and our agonised awareness of the world's harsh injustices and of our own mortality, as against the mysteries of divine justice and immortality."));
        books.add(new Book(7, "The Lord of the Rings", "J. R. R. Tolkien", 1216, "https://kbimages1-a.akamaihd.net/dd36e70a-9657-48c0-bcb7-6333aecb4394/1200/1200/False/the-lord-of-the-rings-1.jpg", "Continuing the story of The Hobbit, this three-volume boxed set of Tolkien's epic masterpiece, The Lord of the Rings, features striking black covers based on Tolkien's own design, the definitive text, and three maps including a detailed map of Middle-earth.", "Sauron, the Dark Lord, has gathered to him all the Rings of Power - the means by which he intends to rule Middle-earth. All he lacks in his plans for dominion is the One Ring - the ring that rules them all - which has fallen into the hands of the hobbit, Bilbo Baggins.\n" +
                "\n" +
                "In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.\n" +
                "\n" +
                "Since it was first published in 1954, 'The Lord of the Rings' has been a book people have treasured. Steeped in unrivalled magic and otherworldliness, its sweeping fantasy has touched the hearts of young and old alike."));
        books.add(new Book(8, "Anna Karenina", "Leo Tolstoy", 848, "https://prodimage.images-bn.com/pimages/2940013851351_p0_v1_s1200x630.jpg", "Anna Karenina is one of the most loved and memorable heroines of literature. Her overwhelming charm dominates a novel of unparalleled richness and density.", "Tolstoy considered this book to be his first real attempt at a novel form, and it addresses the very nature of society at all levels,- of destiny, death, human relationships and the irreconcilable contradictions of existence. It ends tragically, and there is much that evokes despair, yet set beside this is an abounding joy in life's many ephemeral pleasures, and a profusion of comic relief."));
        books.add(new Book(9, "The Picture of Dorian Gray", " Oscar Wilde", 224, "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/8532/9781853260155.jpg", "Wilde's only novel, first published in 1890, is a brilliantly designed puzzle, intended to tease conventional minds with its exploration of the myriad interrelationships between art, life, and consequence. ", "From its provocative Preface, challenging the reader to believe in 'art for art's sake', to its sensational conclusion, the story self-consciously experiments with the notion of sin as an element of design.\n" +
                "\n" +
                "Yet Wilde himself underestimated the consequences of his experiment, and its capacity to outrage the Victorian establishment. Its words returned to haunt him in his court appearances in 1895, and he later recalled the 'note of doom' which runs like 'a purple thread' through its carefully crafted prose."));
        books.add(new Book(10, "Pride and Prejudice", "Jane Austen", 352, "https://d1w7fb2mkkr3kw.cloudfront.net/assets/images/book/lrg/9781/8532/9781853260001.jpg", "Pride and Prejudice, which opens with one of the most famous sentences in English Literature, is an ironic novel of manners.", " In it the garrulous and empty-headed Mrs Bennet has only one aim - that of finding a good match for each of her five daughters. In this she is mocked by her cynical and indolent husband.\n" +
                "\n" +
                "With its wit, its social precision and, above all, its irresistible heroine, Pride and Prejudice has proved one of the most enduringly popular novels in the English language."));
        books.add(new Book(11, "Lolita", "Vadimir Nabokov", 331, "https://www.delfi.rs/_img/artikli/2016/04/lolita_vv.jpg", "Lolita (1955) is frequently cited as his most important novel, and is at any rate his most widely known one, exhibiting the love of intricate wordplay and descriptive detail that characterized all his works.", "Humbert Humbert - scholar, aesthete and romantic - has fallen completely and utterly in love with Lolita Haze, his landlady's gum-snapping, silky skinned twelve-year-old daughter. Reluctantly agreeing to marry Mrs Haze just to be close to Lolita, Humbert suffers greatly in the pursuit of romance; but when Lo herself starts looking for attention elsewhere, he will carry her off on a desperate cross-country misadventure, all in the name of Love. Hilarious, flamboyant, heart-breaking and full of ingenious word play, Lolita is an immaculate, unforgettable masterpiece of obsession, delusion and lust."));
        books.add(new Book(12, "Montana Sky", "Nora Roberts", 438, "https://img.thriftbooks.com/api/images/i/m/4E9D7BC4847A0BA463A766B824C338DE413D4521.jpg", "#1 New York Times bestselling author Nora Roberts presents a novel as sweeping and extraordinary as the Montana sky. . . . When Jack Mercy died, he left behind a ranch worth nearly twenty million dollars.", "When Jack Mercy died, he left behind a ranch worth nearly twenty million dollars. +\nNow his three daughters—each born of a different mother, and each unknown by the others—are gathered to hear the reading of the will. But the women are shocked to learn that before any of them can inherit, they must live together on the ranch for one year. For Tess, a screenwriter who just wants to collect her cash and get back to Hollywood, it’s a nightmare. For Lily, on the run from her abusive ex-husband, it’s a refuge. And for Willa—who grew up on the ranch—it’s an intrusion into her rightful home.They are sisters…and strangers. Now they face a challenge: to put their bitterness aside and live like a family. To protect each other from danger—and unite against a brutal enemy who threatens to destroy them all…"));
        books.add(new Book(13, "Angels Fall", "Nora Roberts", 391, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1442931263l/26050._SY475_.jpg", "#1 New York Times bestselling author Nora Roberts explores the wilds of the Grand Tetons--and the mysteries of love, murder, and madness--in this engrossing and passionate novel.", "Reece Gilmore has come a long way to see the stunning view below her. As the sole survivor of a brutal crime back East, she has been on the run, desperately fighting the nightmares and panic attacks that haunt her. Reece settles in Angel's Fist, Wyoming-temporarily, at least-and takes a job at a local diner. And now she's hiked this mountain all by herself. It was glorious, she thought, as she peered through her binoculars at the Snake River churning below.\n" +
                "\n" +
                "Then Reece saw the man and woman on the opposite bank. Arguing. Fighting. And suddenly, the man was on top of the woman, his hands around her throat . . .\n" +
                "\n" +
                "Enjoying a moment of solitude a bit farther down the trail is a gruff loner named Brody. But by the time Reece reaches him and brings him to the scene, the pair has vanished. When authorities comb the area where she saw the attack, they find nothing. No signs of struggle. No freshly turned earth. Not even a tire track.\n" +
                "\n" +
                "And no one in Angel's Fist seems to believe her. After all, she's a newcomer in town, with a reputation for being jumpy and jittery-maybe even a little fragile. Maybe it's time to run again, to move on . . .\n" +
                "\n" +
                "Reece Gilmore knows there's a killer in Angel's Fist, even if Brody, despite his seeming impatience and desire to keep her at arm's length, is the only one willing to believe her. When a series of menacing events makes it clear that someone wants her out of the way, Reece must put her trust in Brody-and herself-to find out if there is a killer in Angel's Fist before it's too late."));
        books.add(new Book(14, "Women Who Run With the Wolves", "Clarissa Pinkola Estés", 560, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1500974527l/241823._SY475_.jpg", "Myths and Stories of the Wild Woman Archetype", "Within every woman there is a wild and natural creature, a powerful force, filled with good instincts, passionate creativity, and ageless knowing. Her name is Wild Woman, but she is an endangered species. Clarissa Pinkola Estes, Ph.D., Jungian analyst and cantadora storyteller shows how women's vitality can be restored through what she calls \"psychic archeological digs\" into the ruins of the female unconsious. Using multicultural myths, fairy tales, folk tales, and stories, Dr. Estes helps women reconnect with the healthy, instinctual, visionary attributes of the Wild Woman archetype.\n" +
                "\n" +
                "Dr. Estes has created a new lexicon for describing the female psyche. Fertile and life-giving, it is a psychology of women in the truest sense, a knowing of the soul."));
        books.add(new Book(15, "Civilization and Its Discontents", " Sigmund Freud", 127, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1438544596l/357636._SY475_.jpg", "It stands as a brilliant summary of the views on culture from a psychoanalytic perspective that he had been developing since the turn of the century.", "It is both witness and tribute to the late theory of mind—the so-called structural theory, with its stress on aggression, indeed the death drive, as the pitiless adversary of eros.\n" +
                "\n" +
                "Civilization and Its Discontents is one of the last of Freud's books, written in the decade before his death and first published in German in 1929. In it he states his views on the broad question of man's place in the world, a place Freud defines in terms of ceaseless conflict between the individual's quest for freedom and society's demand for conformity.\n" +
                "\n" +
                "\n" +
                "Freud's theme is that what works for civilization doesn't necessarily work for man. Man, by nature aggressive and egotistical, seeks self-satisfaction. But culture inhibits his instinctual drives. The result is a pervasive and familiar guilt.\n" +
                "\n" +
                "\n" +
                "Of the various English translations of Freud's major works to appear in his lifetime, only one was authorized by Freud himself: The Standard Edition of the Complete Psychological Works of Sigmund Freud under the general editorship of James Strachey.\n" +
                "\n" +
                "\n" +
                "Freud approved the overall editorial plan, specific renderings of key words and phrases, and the addition of valuable notes, from bibliographical and explanatory. Many of the translations were done by Strachey himself; the rest were prepared under his supervision. The result was to place the Standard Edition in a position of unquestioned supremacy over all other existing versions."));
        books.add(new Book(16, "The Art of Loving", " Erich Fromm", 192, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1438550243l/14142._SY475_.jpg", "The fiftieth Anniversary Edition of the groundbreaking international bestseller that has shown millions of readers how to achieve rich, productive lives by developing their hidden capacities for love", "Most people are unable to love on the only level that truly matters: love that is compounded of maturity, self-knowledge, and courage. As with every art, love demands practice and concentration, as well as genuine insight and understanding.\n" +
                "\n" +
                "In his classic work, The Art of Loving, renowned psychoanalyst and social philosopher Erich Fromm explores love in all its aspects—not only romantic love, steeped in false conceptions and lofty expectations, but also brotherly love, erotic love, self-love, the love of God, and the love of parents for their children."));
        books.add(new Book(17, "The Subtle Art of Not Giving a F*ck", "Mark Manson", 224, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1465761302l/28257707.jpg", "A Counterintuitive Approach to Living a Good Life", "In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be \"positive\" all the time so that we can truly become better, happier people.\n" +
                "\n" +
                "For decades, we’ve been told that positive thinking is the key to a happy, rich life. \"F**k positivity,\" Mark Manson says. \"Let’s be honest, shit is f**ked and we have to live with it.\" In his wildly popular Internet blog, Manson doesn’t sugarcoat or equivocate. He tells it like it is—a dose of raw, refreshing, honest truth that is sorely lacking today. The Subtle Art of Not Giving a F**k is his antidote to the coddling, let’s-all-feel-good mindset that has infected American society and spoiled a generation, rewarding them with gold medals just for showing up.\n" +
                "\n" +
                "Manson makes the argument, backed both by academic research and well-timed poop jokes, that improving our lives hinges not on our ability to turn lemons into lemonade, but on learning to stomach lemons better. Human beings are flawed and limited—\"not everybody can be extraordinary, there are winners and losers in society, and some of it is not fair or your fault.\" Manson advises us to get to know our limitations and accept them. Once we embrace our fears, faults, and uncertainties, once we stop running and avoiding and start confronting painful truths, we can begin to find the courage, perseverance, honesty, responsibility, curiosity, and forgiveness we seek."));
        books.add(new Book(18, "Emotional Intelligence", "Daniel Goleman", 384, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1388185411l/26329.jpg", "Why It Can Matter More Than IQ", "Everyone knows that high IQ is no guarantee of success, happiness, or virtue, but until Emotional Intelligence, we could only guess why. Daniel Goleman's brilliant report from the frontiers of psychology and neuroscience offers startling new insight into our \"two minds\"—the rational and the emotional—and how they together shape our destiny.\n" +
                "\n" +
                "Through vivid examples, Goleman delineates the five crucial skills of emotional intelligence, and shows how they determine our success in relationships, work, and even our physical well-being. What emerges is an entirely new way to talk about being smart.\n" +
                "\n" +
                "The best news is that \"emotional literacy\" is not fixed early in life. Every parent, every teacher, every business leader, and everyone interested in a more civil society, has a stake in this compelling vision of human possibility."));
        books.add(new Book(19, "The Rise and Fall of the Third Reich", "William L. Shirer", 1614, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1331223772l/767171.jpg", "A History of Nazi Germany", "Hitler boasted that The Third Reich would last a thousand years. It lasted only 12. But those 12 years contained some of the most catastrophic events Western civilization has ever known.\n" +
                "No other powerful empire ever bequeathed such mountains of evidence about its birth and destruction as the Third Reich. When the bitter war was over, and before the Nazis could destroy their files, the Allied demand for unconditional surrender produced an almost hour-by-hour record of the nightmare empire built by Adolph Hitler. This record included the testimony of Nazi leaders and of concentration camp inmates, the diaries of officials, transcripts of secret conferences, army orders, private letters—all the vast paperwork behind Hitler's drive to conquer the world.\n" +
                "\n" +
                "The famed foreign correspondent and historian William L. Shirer, who had watched and reported on the Nazis since 1925, spent five and a half years sifting through this massive documentation. The result is a monumental study that has been widely acclaimed as the definitive record of one of the most frightening chapters in the history of mankind.\n" +
                "\n" +
                "This worldwide bestseller has been acclaimed as the definitive book on Nazi Germany; it is a classic work."));
        books.add(new Book(20, "Beleške jedne Ane", "Momo Kapor", 358, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1399033830l/13271888.jpg", "Književni fenomen Mome Kapora prisutan je u našoj književnosti više od dve decenije. Jedan od najčitanijih naših pisaca", "Kaporovo umeće fascinacije zasniva se na različitim znanjima i istančanim darovima opažanja i raščlanjavanja stvarnosti i oblika života, njegovih pojavnih formi i dubina. Svedočeći uvek iz vremena, Kapor našem vremenu dodaje njegovu zaboravljenu korensku povezanost koja u formama svakodnevnih gestova, pamćenja i likova oblikuje njegove junake i obeležava njihovu sudbinu. Kaporova pristrasnost kao pisca, od one je pristrasnosti koja je na strani čitaoca, na strani onih oblika oslobađanja od predrasuda koje bi da nas odvezu od emocija i čistote neposrednosti i bliskosti malih stvari i topline mitologija preživljavanja. Kaporov sentimentalizam i elegantna ironičnost su oblik odbrane od nerasudnih snaga sveta zla i života."));
        books.add(new Book(21, "Kroz vasionu i vekove", "Milutin Milankovic", 404, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1448020416l/22045520._SY475_.jpg", "\"Kroz vasionu i vekove\" Milutina Milankovića je naučna istorija astronomije, ali i izuzetna epistolarna i putopisna proza.", "irinom imaginacije i veštinom tumačenja naučnih ideja, lepotom pričanja o drevnim prilikama i bogatstvom jezika i stila ona daleko prevazilazi naučne bestselere XX veka, poput \"Kratke povesti vremena\" Stivena Hokinga, \"Kosmosa\" Karla Sagana, istorije vaseljene nobelovca Liona Ledermana ili \"Snova o konačnoj teoriji\" nobelovca Stivena Vajnberga."));
        books.add(new Book(22, "The Kite Runner", "Khaled Hosseini", 371, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1579036753l/77203._SY475_.jpg", "The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father’s servant.", "The Kite Runner is a beautifully crafted novel set in a country that is in the process of being destroyed. It is about the power of reading, the price of betrayal, and the possibility of redemption; and an exploration of the power of fathers over sons—their love, their sacrifices, their lies.\n" +
                "\n" +
                "A sweeping story of family, love, and friendship told against the devastating backdrop of the history of Afghanistan over the last thirty years, The Kite Runner is an unusual and powerful novel that has become a beloved, one-of-a-kind classic.\n" +
                "--khaledhosseini.com"));
        books.add(new Book(23, "A Thousand Splendid Suns", "Khaled Hosseini", 372, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1345958969l/128029.jpg", " is a breathtaking story set against the volatile events of Afghanistan's last thirty years—from the Soviet invasion to the reign of the Taliban to post-Taliban rebuilding—that puts the violence, fear, hope, and faith of this country in intimate, human terms.", "It is a tale of two generations of characters brought jarringly together by the tragic sweep of war, where personal lives—the struggle to survive, raise a family, find happiness—are inextricable from the history playing out around them.\n" +
                "\n" +
                "Propelled by the same storytelling instinct that made The Kite Runner a beloved classic, A Thousand Splendid Suns is at once a remarkable chronicle of three decades of Afghan history and a deeply moving account of family and friendship. It is a striking, heart-wrenching novel of an unforgiving time, an unlikely friendship, and an indestructible love—a stunning accomplishment."));
        books.add(new Book(24, "Eat, Pray, Love", "Elizabeth Gilbert", 368, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1503066414l/19501.jpg", "A celebrated writer's irresistible, candid, and eloquent account of her pursuit of worldly pleasure, spiritual devotion, and what she really wanted out of life.", "Around the time Elizabeth Gilbert turned thirty, she went through an early-onslaught midlife crisis. She had everything an educated, ambitious American woman was supposed to want—a husband, a house, a successful career. But instead of feeling happy and fulfilled, she was consumed with panic, grief, and confusion. She went through a divorce, a crushing depression, another failed love, and the eradication of everything she ever thought she was supposed to be.\n" +
                "\n" +
                "To recover from all this, Gilbert took a radical step. In order to give herself the time and space to find out who she really was and what she really wanted, she got rid of her belongings, quit her job, and undertook a yearlong journey around the world—all alone. Eat, Pray, Love is the absorbing chronicle of that year. Her aim was to visit three places where she could examine one aspect of her own nature set against the backdrop of a culture that has traditionally done that one thing very well. In Rome, she studied the art of pleasure, learning to speak Italian and gaining the twenty-three happiest pounds of her life. India was for the art of devotion, and with the help of a native guru and a surprisingly wise cowboy from Texas, she embarked on four uninterrupted months of spiritual exploration. In Bali, she studied the art of balance between worldly enjoyment and divine transcendence. She became the pupil of an elderly medicine man and also fell in love the best way—unexpectedly.\n" +
                "\n" +
                "An intensely articulate and moving memoir of self-discovery, Eat, Pray, Love is about what can happen when you claim responsibility for your own contentment and stop trying to live in imitation of society’s ideals. It is certain to touch anyone who has ever woken up to the unrelenting need for change."));
        books.add(new Book(25, "Madame Bovary", "Gustave Flaubert", 329, "https://prodimage.images-bn.com/pimages/9781455330546_p0_v5_s550x406.jpg", "'Oh, why, dear God, did I marry him?'", "Emma Bovary is beautiful and bored, trapped in her marriage to a mediocre doctor and stifled by the banality of provincial life. An ardent devourer of sentimental novels, she longs for passion and seeks escape in fantasies of high romance, in voracious spending and, eventually, in adultery. But even her affairs bring her disappointment, and when real life continues to fail to live up to her romantic expectations, the consequences are devastating. Flaubert's erotically charged and psychologically acute portrayal of Emma Bovary caused a moral outcry on its publication in 1857. It was deemed so lifelike that many women claimed they were the model for his heroine; but Flaubert insisted: 'Madame Bovary, c'est moi.'\n" +
                "\n" +
                "This modern translation by Flaubert's biographer, Geoffrey Wall, retains all the delicacy and precision of the French original. The edition also contains a preface by the novelist Michèle Roberts."));
        books.add(new Book(26, "Perfume", " Patrick Süskind", 263, "https://images-na.ssl-images-amazon.com/images/I/915ZvJAtO0L.jpg", "The Story of a Murderer", "An acclaimed bestseller and international sensation, Patrick Suskind's classic novel provokes a terrifying examination of what happens when one man's indulgence in his greatest passion—his sense of smell—leads to murder.\n" +
                "\n" +
                "In the slums of eighteenth-century France, the infant Jean-Baptiste Grenouille is born with one sublime gift—an absolute sense of smell. As a boy, he lives to decipher the odors of Paris, and apprentices himself to a prominent perfumer who teaches him the ancient art of mixing precious oils and herbs. But Grenouille's genius is such that he is not satisfied to stop there, and he becomes obsessed with capturing the smells of objects such as brass doorknobs and fresh-cut wood. Then one day he catches a hint of a scent that will drive him on an ever-more-terrifying quest to create the \"ultimate perfume\"—the scent of a beautiful young virgin. Told with dazzling narrative brilliance, Perfume is a hauntingly powerful tale of murder and sensual depravity."));
        books.add(new Book(27, "Antígona", "Sophocles", 32, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1547124208l/43528907._SY475_.jpg", "The curse placed on Oedipus lingers and haunts a younger generation in this new and brilliant translation of Sophocles' classic drama.", "The daughter of Oedipus and Jocasta, Antigone is an unconventional heroine who pits her beliefs against the King of Thebes in a bloody test of wills that leaves few unharmed. Emotions fly as she challenges the king for the right to bury her own brother. Determined but doomed, Antigone shows her inner strength throughout the play.\n" +
                "\n" +
                "Antigone raises issues of law and morality that are just as relevant today as they were more than two thousand years ago. Whether this is your first reading or your twentieth, Antigone will move you as few pieces of literature can.\n" +
                "\n" +
                "To make this quintessential Greek drama more accessible to the modern reader, this Prestwick House Literary Touchstone Edition includes a glossary of difficult terms, a list of vocabulary words, and convenient sidebar notes. By providing these, it is our intention that readers will more fully enjoy the beauty, wisdom, and intent of the play."));
        books.add(new Book(28, "The House of the Spirits", "Isabel Allende ", 448, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1358615501l/9328.jpg", "In one of the most important and beloved Latin American works of the twentieth century, Isabel Allende weaves a luminous tapestry of three generations of the Trueba family, revealing both triumphs and tragedies.", "Here is patriarch Esteban, whose wild desires and political machinations are tempered only by his love for his ethereal wife, Clara, a woman touched by an otherworldly hand. Their daughter, Blanca, whose forbidden love for a man Esteban has deemed unworthy infuriates her father, yet will produce his greatest joy: his granddaughter Alba, a beautiful, ambitious girl who will lead the family and their country into a revolutionary future.\n" +
                "\n" +
                "The House of the Spirits is an enthralling saga that spans decades and lives, twining the personal and the political into an epic novel of love, magic, and fate."));
        books.add(new Book(29, "The Old Man and the Sea", "Ernest Hemingway", 96, "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1329189714l/2165.jpg", "Written in 1952, this hugely successful novella confirmed his power and presence in the literary world and played a large part in his winning the 1954 Nobel Prize for Literature.", "The Old Man and the Sea is one of Hemingway’s most enduring works. Told in language of great simplicity and power, it is the story of an old Cuban fisherman, down on his luck, and his supreme ordeal—a relentless, agonizing battle with a giant marlin far out in the Gulf Stream. Here Hemingway recasts, in strikingly contemporary style, the classic theme of courage in the face of defeat, of personal triumph won from loss."));
        return books;
    }
}
